### ISSUE TITLE
Pick a different shortcut

### ISSUE THREAD

**Issue by njx** [njx/brackets-bower#11]
Need to pick a different shortcut before the multiselect stuff in cmv4 lands, since Ctrl-Shift-B is being used by Skip Next Match.

**Comment by albertinad** [comment]
Hi @njx I will close this issue since the current command for the extension is "Ctrl+Alt+B". In the case of having problems with that command I will file another issue.

**Comment by njx** [comment]
Sounds good, and thanks for all your continued work on this.
