### ISSUE TITLE
Error with Bower

### ISSUE THREAD

**Issue by MrAshTonka** [njx/brackets-bower#24]
Trying to install a package for my project but i get this errors every time i open Bower in Brackets, I have the latest copy of it as i only installed Brackets 2 days ago.

Uncaught TypeError: Cannot read property 'done' of null  -  QuickInstall.js:194
_search  -  QuickInstall.js:194
QuickNavigateDialog._filterCallback  -  /search/QuickOpen.js:635
(anonymous function)  -  /thirdparty/smart-auto-complete-local/jquery.smart_autocomplete.js:165

**Comment by albertinad** [comment]
I @MrAshTonka , I took a look at this, I found the main cause of this bug. Nice catch! It will be fixed in the next release. I will keep you posted when it is done.
Thanks!

**Comment by albertinad** [comment]
Fixed. It will be available in the next version of brackets-bower in a few days. The fix is already at master branch. Closing the issue, if the bug is replicated again, I will reopen it.
Thanks!
