### ISSUE TITLE
Update Panel buttons with Icons

### ISSUE THREAD

**Issue by albertinad** [njx/brackets-bower#28]
Add icons for:
* Configuration
* Dependencies
* Extension Settings

**Comment by navelpluisje** [comment]
@albertinad I'm currently working on this one. I'm using the octicons set.
![schermafbeelding 2015-01-25 om 22 05 24](https://cloud.githubusercontent.com/assets/1625221/5893288/55700346-a4de-11e4-8a4b-9637f57ceedf.png)

**Comment by albertinad** [comment]
Awesome! I like those ones. Please add it to the html files for configuration and dependencies, not need for now the one for installing packages.

**Comment by albertinad** [comment]
Solved in PR #32 
Closing.
