### ISSUE TITLE
Update extension information

### ISSUE THREAD

**Issue by albertinad** [njx/brackets-bower#39]
Hi @njx , I will update the extension title at the package.json from "Install from Bower" to "Brackets Bower", a more representative name for what the extension does, since the new version that I will upload to the registry has support for install and prune, and bower metadata files like .bowerrc and bower.json handling. 
In future releases those features will be improved and new commands will be supported.
If you have any questions please let me know :)

**Comment by njx** [comment]
Perfect! You've really extended this in ways I hadn't even thought about.

**Comment by njx** [comment]
Hey, at this point should we just make your repo the official fork? There really isn't any reason to have you push into this repo since you really own it at this point. You could change the repo link in the package.json, and update the README here to indicate that it's no longer the main repo.

**Comment by njx** [comment]
(Oh - I guess the issues are still being maintained here, so maybe that's a reason to keep this alive.)

**Comment by albertinad** [comment]
Thanks :D Yes, I can migrate the issues to my repo and then make it the official repo.

**Comment by albertinad** [comment]
Ni @njx ! I was thinking about making my fork the official repo. What do you think about transfer this repo to me, in that way we keep the issues and PR in process, the users that forked this repo will only need to update the remote url, and any change that I make will be counted as a contribution on github, that will not happen if I work only on my fork. As part of the transfer, you will still be an official collaborator. Let me know what do you think :)

**Comment by njx** [comment]
Oh yeah, I totally forgot we could just transfer the repo. If I do that right now, will it mess up your fork (since it has the same name)? Let me know when you want me to do the transfer and I'll do it.
