### ISSUE TITLE
Filename is not appearing in the correct position

### ISSUE THREAD

**Issue by aniforprez** [njx/brackets-bower#43]
The bower extension panel panel isn't placing the bower files' names in the proper location as seen in this screenshot:

![image](https://cloud.githubusercontent.com/assets/993132/6317645/17ac79a0-ba86-11e4-9aab-ee23c3025bef.png)

**Comment by albertinad** [comment]
Hi @aniforprez I think that this could be related to some styles that are being replaced by other extensions. Could you please give me the extensions name that you have installed? Thanks!

**Comment by aniforprez** [comment]
Of course!

* Advanced New File
* Angular Snippets
* Angular JS Code Hints
* AngularJS for Brackets
* Better quotes for Brackets
* Brackets Bower
* Brackets File Icons
* Brackets Git
* Brackets New Project Creator
* Brackets Outline List
* Brackets Snippets
* Code Folding
* CSSLint
* Documents Toolbar
* Emmet
* Extensions Rating
* File Tree Exclude
* FuncDocr
* Grunt for Brackets
* HTMLHint
* Indent Guides
* Indentator
* JSHint
* Lines of Code Counter for Javascript
* Markdown Preview
* Material-Angular JS Code Hints
* QuickDocsJS
* Reasonable Comments
* Rename Javascript Identifier
* SASSHints
* Semicenter
* Theseus for Brackets
* Todo

**Comment by aniforprez** [comment]
A thousand apologies. I closed the issue by accident.

**Comment by albertinad** [comment]
No problem! :) thanks! I will take a look at this.

**Comment by albertinad** [comment]
The fix is ready, but not yet uploaded to the brackets registry. You can download the zip package related to the new version from here, 
[https://github.com/njx/brackets-bower/releases/tag/v0.2.2](https://github.com/njx/brackets-bower/releases/tag/v0.2.2)
then drag it to the extension manager in brackets or decompress it to the brackets user folder extensions.
Thanks!

**Comment by aniforprez** [comment]
Thanks for the fix!
