### ISSUE TITLE
Warn user if git isn't installed

### ISSUE THREAD

**Issue by njx** [njx/brackets-bower#6]
It looks like Bower requires git to be installed in order to install some (many?) packages. I added notes to the README and package description, but it would be good to actually detect this in the extension itself and warn the user if they try to install a package that requires git.

**Comment by albertinad** [comment]
Hi @njx ! I implemented this validation when the extension initializes. It checks if Git is found at the system PATH, if not, it shows a warning message to the user. The implementation is already at the master branch and will be available in the next release. Feel free to take a look at it :)

I'm closing this issue.

**Comment by njx** [comment]
Sounds good, thanks.
